import React from "react";

const About = () => {


  return (
    <section className="relative z-10 text-white md:px-12 lg:px-24">
      <div className="w-[80%] m-auto sm:max-w-4xl flex flex-col justify-center sm:justify-start text-start sm:ml-20 space-y-8">
        <div
          data-aos="fade-up"
          data-aos-duration="1000"
          className="space-y-6 text-[14px] text-gray-300/90 leading-relaxed"
        >
          <p className="text-2xl sm:text-3xl font-bold">Hey, I'm Aayush</p>
          <p>
            I'm a passionate{" "}
            <span className="font-medium">Full Stack Developer</span> with
            hands-on experience in building modern <br /> web solutions. My
            expertise includes working with the MERN stack and developing
            backends <br /> using Python with FastAPI. Additionally, I have a
            knack for creating AI-powered applications.
          </p>
          <p>
            I've had the pleasure of working on a variety of exciting projects,
            including a <span className="font-semibold ">Chatbot</span>,
            real-time chat <br /> applications, video calling features, an
            AI-powered resume builder, and full-stack websites. My most <br />{" "}
            recent project, the <span className="font-semibold ">Chatbot</span>,
            allows users to interact with an intelligent assistant, ask
            questions, and even <br /> send emails on their behalf.
          </p>
          <p>
            Currently, I'm diving into{" "}
            <span className="font-medium text-purple-400">AI</span> and trying
            to collaborating projects!
          </p>
          <p className="text-[13px] text-blue-300"> My resume that you're viewing was generated by my resume generator.</p>
        </div>
        <div className="mt-4" data-aos="fade-up" data-aos-duration="1000">
          <a
            href="https://linkedin.com/in/ayushghimiree"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block border border-gray-600 text-white px-5 py-2 sm:px-8 sm:py-3 rounded-full text-[14px] sm:text-lg hover:bg-gray-700 transition-all duration-300 shadow-lg hover:shadow-xl hover:scale-105"
          >
            Connect with Me
          </a>
        </div>
      </div>
    </section>
  );
};

export default About;
